"""Tests for the formalization agent response schema.

Definitions (predicate/constant mappings) are now Python-generated by the
normalizer and no longer part of the LLM response schema.
"""

import json
import pytest
from services.agent_prompts import agent_gpt_formalize

try:
    from jsonschema import validate, ValidationError
    JSONSCHEMA_AVAILABLE = True
except ImportError:
    JSONSCHEMA_AVAILABLE = False


def test_formalization_schema_validity():
    """Schema is valid JSON and has the required structure."""
    schema = agent_gpt_formalize.response_format_base

    json.dumps(schema)  # must not raise

    assert schema["type"] == "object"
    assert "properties" in schema
    assert "required" in schema

    # formalizations array
    fmls = schema["properties"]["formalizations"]
    assert fmls["type"] == "array"
    item_props = fmls["items"]["properties"]
    assert item_props["symbol"]["type"] == "string"
    assert item_props["ascii"]["type"] == "string"
    assert item_props["json_structure"]["type"] == "string"
    assert fmls["items"]["additionalProperties"] is False

    # confidence and reasoning
    assert schema["properties"]["confidence"]["type"] == "number"
    assert schema["properties"]["reasoning"]["type"] == "string"

    # required fields — definitions is no longer in the model's output
    required = schema["required"]
    assert "formalizations" in required
    assert "confidence" in required
    assert "reasoning" in required
    assert "definitions" not in required

    assert schema["additionalProperties"] is False


def test_schema_matches_example():
    """Schema accepts a well-formed response with semantic predicate names."""
    example_response = {
        "formalizations": [
            {
                "symbol": "1",
                "ascii": "is_man(socrates)",
                "json_structure": json.dumps({
                    "type": "predicate", "pred_const": "is_man",
                    "args": [{"type": "constant", "name": "socrates"}]
                })
            },
            {
                "symbol": "2",
                "ascii": "forall individual. (is_man(individual) -> is_mortal(individual))",
                "json_structure": json.dumps({
                    "type": "quantifier", "quant": "forall",
                    "var": {"type": "variable", "name": "individual"},
                    "body": {
                        "type": "binary", "op": "implies",
                        "left": {"type": "predicate", "pred_const": "is_man",
                                 "args": [{"type": "variable", "name": "individual"}]},
                        "right": {"type": "predicate", "pred_const": "is_mortal",
                                  "args": [{"type": "variable", "name": "individual"}]}
                    }
                })
            },
            {
                "symbol": "3",
                "ascii": "is_mortal(socrates)",
                "json_structure": json.dumps({
                    "type": "predicate", "pred_const": "is_mortal",
                    "args": [{"type": "constant", "name": "socrates"}]
                })
            }
        ],
        "confidence": 0.95,
        "reasoning": "Classic syllogism with semantic predicate names"
    }

    assert "formalizations" in example_response
    assert "confidence" in example_response
    assert "reasoning" in example_response
    assert "definitions" not in example_response  # Python generates this now

    for fml in example_response["formalizations"]:
        assert "symbol" in fml
        assert "ascii" in fml
        assert "json_structure" in fml
        assert isinstance(fml["json_structure"], str)
        # json_structure must be parseable
        parsed = json.loads(fml["json_structure"])
        assert "type" in parsed


@pytest.mark.skipif(not JSONSCHEMA_AVAILABLE, reason="jsonschema library not available")
def test_schema_json_validation():
    """jsonschema library validates a conforming response and rejects missing required fields."""
    schema = agent_gpt_formalize.response_format_base

    valid_response = {
        "formalizations": [
            {
                "symbol": "1",
                "ascii": "is_man(socrates)",
                "json_structure": json.dumps({
                    "type": "predicate", "pred_const": "is_man",
                    "args": [{"type": "constant", "name": "socrates"}]
                })
            }
        ],
        "confidence": 0.95,
        "reasoning": "Test reasoning"
    }
    validate(instance=valid_response, schema=schema)

    invalid_response = {
        "formalizations": [
            {"symbol": "1", "ascii": "is_man(socrates)",
             "json_structure": "{}"}
        ],
        "confidence": 0.95
        # missing "reasoning"
    }
    with pytest.raises(ValidationError):
        validate(instance=invalid_response, schema=schema)


def test_schema_openai_compatibility():
    """All type values are OpenAI-compatible and additionalProperties is boolean when present."""
    schema = agent_gpt_formalize.response_format_base
    valid_types = {"object", "array", "string", "number", "integer", "boolean"}

    def check(obj):
        if isinstance(obj, dict):
            if "type" in obj:
                assert obj["type"] in valid_types, f"Invalid type: {obj['type']}"
            if "additionalProperties" in obj:
                assert isinstance(obj["additionalProperties"], bool)
            for v in obj.values():
                check(v)
        elif isinstance(obj, list):
            for item in obj:
                check(item)

    check(schema)
